name: Purge Cloudflare Cache
on:
  push:
    branches:
      - master
jobs:
  wait-for-vercel-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: UnlyEd/github-action-await-vercel@v1.1.0
        id: await-vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          deployment-url: pm2.vercel.app
          timeout: 600 # Wait for 10 minutes before failing
  purge-cache:
    runs-on: ubuntu-latest
    needs: wait-for-vercel-deployment
    steps:
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
